name: learning_english_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  loading_animation_widget: ^1.1.0+3
  flutter_dotenv: ^5.0.2
  rounded_loading_button: ^2.1.0
  salomon_bottom_bar: ^3.2.0
  smooth_page_indicator: ^1.0.0+2
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  fluttertoast: ^8.0.9
  motion_toast: ^2.1.3
  floor: ^1.2.0
  device_info_plus: ^3.2.2
  settings_ui: ^2.0.2
  flutter_otp_text_field: ^1.0.0
  google_sign_in: ^5.2.4
  flutter_easyloading: ^3.0.3
  logger_flutter: ^0.7.1
  flutter_facebook_auth: ^4.1.2
  shimmer: ^2.0.0
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  firebase_storage: ^10.2.11
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  percent_indicator: ^4.0.0
  font_awesome_flutter: ^9.2.0
  async: ^2.8.2
  package_info_plus: ^1.0.6
  firebase_core: ^1.15.0
  swipeable_card_stack: ^0.0.5
  just_audio: ^0.9.20
  flutter_staggered_animations: ^1.0.0
  timelines: ^0.1.0
  pin_code_fields: ^7.4.0
  pinput: ^2.2.7
  animated_flip_counter: ^0.2.4
  dotted_border: ^2.0.0+1
  tcard: ^1.3.5
  flip_card: ^0.6.0
  like_button: ^2.0.4
  material_floating_search_bar: ^0.3.7
  dropdown_button2: ^1.4.0
  flutter_scrolling_fab_animated: ^0.1.3+2
  flutter_slidable: ^1.3.0
  awesome_notifications: ^0.6.21
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  json_serializable: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"  

flutter_native_splash:
  color: "#ffffff"
  image:  "assets/icon/icon.png"  
  color_dark: "#121212"
  image_dark:  "assets/icon/icon.png"  

  android_12:
    image:  "assets/icon/icon.png"  
    icon_background_color: "#ffffff"
    image_dark: "assets/icon/icon.png"  
    icon_background_color_dark: "#121212"
  
  web: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/app_data/
  - assets/images/
  - assets/svg/
  - assets/images/subjects/
  - assets/sound/
  - .env.development
  - .env.production
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
